const fs = require('fs');
const f = 'src/pipeline/PipelineRunner.ts';
let c = fs.readFileSync(f, 'utf8');

const oldDrain = `async drain(): Promise<void> {\n    let emptyPolls = 0;\n    const maxEmpty = 2; // drain stops after 2 empty polls in a row\n\n    while (true) {\n      const dequeueResult = await this.queue.dequeue();\n      if (!isOk(dequeueResult)) break;\n\n      const job = dequeueResult.value;\n      if (job === null) {\n        emptyPolls++;\n        if (emptyPolls >= maxEmpty) break;\n        continue;\n      }\n\n      emptyPolls = 0;\n      await this.processJob(job);\n    }\n  }`;

const newDrain = `async drain(): Promise<void> {\n    let emptyPolls = 0;\n    const maxEmpty = 2;\n    let dequeueCount = 0;\n    let ackCount = 0;\n    let nackCount = 0;\n\n    const depthBefore = await this.queue.depth();\n    console.log('[drain:start] queue-depth=' + (isOk(depthBefore) ? depthBefore.value : '?'));\n\n    const origAck = this.queue.ack.bind(this.queue);\n    const origNack = this.queue.nack.bind(this.queue);\n    (this.queue as any).ack = async (id: string) => { ackCount++; return origAck(id); };\n    (this.queue as any).nack = async (id: string, r?: string) => { nackCount++; return origNack(id, r); };\n\n    let exitReason = 'dequeue-error';\n    while (true) {\n      const dequeueResult = await this.queue.dequeue();\n      if (!isOk(dequeueResult)) { exitReason = 'dequeue-error'; break; }\n\n      const job = dequeueResult.value;\n      if (job === null) {\n        emptyPolls++;\n        console.log('[drain:null] emptyPolls=' + emptyPolls + '/' + maxEmpty + ' dequeued=' + dequeueCount);\n        if (emptyPolls >= maxEmpty) { exitReason = 'maxEmpty'; break; }\n        continue;\n      }\n\n      dequeueCount++;\n      emptyPolls = 0;\n      await this.processJob(job);\n    }\n\n    (this.queue as any).ack = origAck;\n    (this.queue as any).nack = origNack;\n\n    const depthAfter = await this.queue.depth();\n    console.log('[drain:end] exit=' + exitReason + ' emptyPolls=' + emptyPolls + ' dequeued=' + dequeueCount + ' acked=' + ackCount + ' nacked=' + nackCount + ' queue-depth-after=' + (isOk(depthAfter) ? depthAfter.value : '?'));\n  }`;

const replaced = c.replace(oldDrain, newDrain);
if (replaced === c) { console.log('FAILED - no match'); process.exit(1); }
fs.writeFileSync(f, replaced, 'utf8');
console.log(replaced.includes('[drain:start]') && replaced.includes('[drain:end]') ? 'OK' : 'FAILED');
